# Generated by Django 6.0.5 on 2026-08-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='map.map'),
            preserve_default=False,
        ),
    ]
